name: sajilo
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  curved_navigation_bar: ^0.3.4
  cupertino_icons: ^0.1.3
  firebase_database: ^4.0.0
  modal_progress_hud: ^0.1.3
  flutter_screen_scaler: ^2.0.0
  provider: ^4.3.2
  firebase_dynamic_links: ^0.6.0
  firebase_auth: ^0.18.0+1
  firebase_core: ^0.5.0+1
  cloud_firestore: "^0.14.1+3"
  google_sign_in: ^4.5.1
  flutter_twitter: ^1.1.3
  flutter_facebook_login: ^3.0.0
  progress_dialog: ^1.2.4
  flutter_spinkit: ^4.1.2+1
  url_launcher: ^5.7.2
  http: any
  firebase_messaging: ^7.0.3
  fluttertoast: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true


  assets:
    - assets/icons/
    - assets/images/
    - assets/serviceimage/ac.png
    - assets/serviceimage/bike.png
    - assets/serviceimage/car.png
    - assets/serviceimage/electricity.png
    - assets/serviceimage/haircut.png
    - assets/serviceimage/laptop.png
    - assets/serviceimage/painting.png
    - assets/serviceimage/tv.png
    - assets/serviceimage/applogo.png
    - assets/serviceimage/furniture.png
    - assets/serviceimage/plumbing.png
    - assets/serviceimage/bg.png
    - assets/appbarimage/house-painting.jpg
    - assets/appbarimage/car.jpg
    - assets/appbarimage/electricity.jpg
    - assets/appbarimage/laptop.png
    - assets/appbarimage/ACRepair.jpg
    - assets/appbarimage/bike.png
    - assets/appbarimage/tvrepair.png
    - assets/appbarimage/barber.jpg
    - assets/appbarimage/plumber.jpg
    - assets/appbarimage/furniture.png


  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Light.ttf
        - asset: assets/fonts/Rubik-Regular.ttf
        - asset: assets/fonts/Rubik-Medium.ttf
        - asset: assets/fonts/Rubik-SemiBold.ttf
        
